defaults: &defaults
  host: pse4.iam.unibe.ch
  port: 27017
  database: admin
  username: pse4_read
  password: plokij

development:
  <<: *defaults
  host: localhost
  username:
  password:

development-remote:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
