defaults: &defaults
  host: pse4.iam.unibe.ch
  port: 27017
  database: admin
  username: pse4_read
  password: plokij
  write_username: pse4_write
  collections: {
    chop_ranges: [chop_ranges_to_fmh, ranges],
    icd_ranges: [icd_ranges_to_fmh, ranges],
    catalogs: {
      icd_2010_ch: {
      de: [icd_2010_ch,de],
      fr: [icd_2010_ch,fr],
      },
      icd_2012_ch: {
      de: [icd_2012_ch,de],
      fr: [icd_2012_ch,fr],
      it: [icd_2012_ch,it],
      en: [icd_2012_ch,en]
      },
      chop_2012_ch: {
      de: [chop_2012_ch,de],
      fr: [chop_2012_ch,fr],
      },
      chop_2013_ch: {
      de: [chop_2013_ch,de],
      fr: [chop_2013_ch,fr],
      it: [chop_2013_ch,it],
    }
  },
  compounds : [fmh_compounds,compounds],
  doctors : [doctors,doctors],
  docfield_to_FMH_code : [doctors,docfield_to_fmh],
  icd_keywords : [dictionaries,icd_dictionary],
  fmh_codes : [fmh,fmh_names],
  mdc_to_fmh : [mdc,mdc_to_fmh],
  mdcs : [mdc,mdc_names],
  thesauri : [thesauren],
  thesaur_to_fs : [thesaur,thesaur_to_fmh],
  thesaur_to_icd : [thesaur, thesaur_to_icd]
  }

development:
  <<: *defaults
  host: localhost
  username:
  password:

development-remote:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
