defaults: &defaults
  host: pse4.iam.unibe.ch
  port: 27017

development:
  <<: *defaults
  database: orange_proton_development

test:
  <<: *defaults
  database: orange_proton_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: orange_proton
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
