defaults: &defaults
  port: 27017

development:
  <<: *defaults
  host: localhost
  database: admin

development-remote:
  <<: *defaults
  host: pse4.iam.unibe.ch
  database: admin
  username: pse4_read
  password: plokij

test:
  <<: *defaults
  host: localhost
  database: admin

# set these environment variables on your prod server
production:
  <<: *defaults
  database: admin
  username: pse4_read
  password: plokij
